[package]
name = "dfkit"
version = "0.1.0"
edition = "2024"

[dependencies]
datafusion = {version = "46.0.1", features = ["avro"]}
structopt = "0.3.26"
thiserror = "2.0.12"
tokio = { version="1.44.2", features = ["rt-multi-thread"]}
